### ISSUE TITLE
Phantom walls

### ISSUE THREAD

**Issue by MichaelWoodburn** [AyazLab/MazeWalker#2]
There seems to be a bug with maze walker that causes walls to be created when they are not placed in maze maker. This is most often the case with curved walls when the program draws a nonexistent wall in between parts of the curved wall creating a fake barrier. Often though there are simply straight walls drawn between parts of the map even if no walls were ever drawn.

**Comment by AdrianCurtin** [comment]
This relates to an issue in MazeMaker fixed in the latest patch
